create table if not exists public.tiendas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null references public.tiendas(id) on delete cascade,
  codigo_barras text not null,
  nombre_producto text not null,
  unidad text not null default 'pieza',
  created_at timestamptz not null default now(),
  unique (tienda_id, codigo_barras)
);

create table if not exists public.conteos (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null references public.tiendas(id) on delete cascade,
  nombre_sesion text not null,
  codigo_acceso text not null,
  estado text not null default 'abierto' check (estado in ('abierto', 'cerrado')),
  created_at timestamptz not null default now()
);

-- Migration for projects created with the first version of the schema.
alter table public.conteos add column if not exists codigo_acceso text;
update public.conteos
set codigo_acceso = upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
where codigo_acceso is null;
alter table public.conteos alter column codigo_acceso set not null;
create unique index if not exists conteos_codigo_acceso_key on public.conteos(codigo_acceso);

create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null references public.tiendas(id) on delete cascade,
  nombre text not null,
  unique (tienda_id, nombre)
);

create table if not exists public.registros_detalle (
  id bigint generated by default as identity primary key,
  conteo_id bigint not null references public.conteos(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete restrict,
  operador_nombre text not null,
  area text not null,
  cantidad numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.productos_no_catalogados (
  id bigint generated by default as identity primary key,
  conteo_id bigint not null references public.conteos(id) on delete cascade,
  nombre_temporal text not null,
  operador_nombre text not null,
  area text not null,
  cantidad numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.tiendas enable row level security;
alter table public.productos enable row level security;
alter table public.conteos enable row level security;
alter table public.areas enable row level security;
alter table public.registros_detalle enable row level security;
alter table public.productos_no_catalogados enable row level security;

create policy "inventario publico tiendas" on public.tiendas for all to anon, authenticated using (true) with check (true);
create policy "inventario publico productos" on public.productos for all to anon, authenticated using (true) with check (true);
create policy "inventario publico conteos" on public.conteos for all to anon, authenticated using (true) with check (true);
create policy "inventario publico areas" on public.areas for all to anon, authenticated using (true) with check (true);
create policy "inventario publico registros" on public.registros_detalle for all to anon, authenticated using (true) with check (true);
create policy "inventario publico no catalogados" on public.productos_no_catalogados for all to anon, authenticated using (true) with check (true);

alter publication supabase_realtime add table public.registros_detalle;
alter publication supabase_realtime add table public.productos_no_catalogados;