alter table public.productos
  add column if not exists es_critico boolean not null default false;

alter table public.tiendas
  add column if not exists codigo_critico text;

update public.tiendas
set codigo_critico = upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
where codigo_critico is null;

alter table public.tiendas
  alter column codigo_critico set default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  alter column codigo_critico set not null;

create unique index if not exists tiendas_codigo_critico_key
  on public.tiendas (codigo_critico);

create table if not exists public.conteos_criticos_diarios (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null references public.tiendas(id) on delete cascade,
  fecha date not null,
  operador_nombre text not null,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'revisado')),
  created_at timestamptz not null default now(),
  revisado_at timestamptz,
  revisado_por uuid references auth.users(id),
  unique (tienda_id, fecha)
);

create table if not exists public.conteos_criticos_detalle (
  conteo_id bigint not null references public.conteos_criticos_diarios(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete restrict,
  cantidad_contada numeric not null check (cantidad_contada >= 0),
  existencia_sistema numeric check (existencia_sistema >= 0),
  primary key (conteo_id, producto_id)
);

create index if not exists conteos_criticos_diarios_tienda_fecha_idx
  on public.conteos_criticos_diarios (tienda_id, fecha desc);

alter table public.conteos_criticos_diarios enable row level security;
alter table public.conteos_criticos_detalle enable row level security;

drop policy if exists "admin gestiona conteos criticos propios" on public.conteos_criticos_diarios;
create policy "admin gestiona conteos criticos propios" on public.conteos_criticos_diarios
for all to authenticated
using (exists (select 1 from public.tiendas t where t.id = tienda_id and t.owner_id = auth.uid()))
with check (exists (select 1 from public.tiendas t where t.id = tienda_id and t.owner_id = auth.uid()));

drop policy if exists "admin gestiona detalle critico propio" on public.conteos_criticos_detalle;
create policy "admin gestiona detalle critico propio" on public.conteos_criticos_detalle
for all to authenticated
using (
  exists (
    select 1 from public.conteos_criticos_diarios cc
    join public.tiendas t on t.id = cc.tienda_id
    where cc.id = conteo_id and t.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.conteos_criticos_diarios cc
    join public.tiendas t on t.id = cc.tienda_id
    where cc.id = conteo_id and t.owner_id = auth.uid()
  )
);

create or replace function public.get_critical_store_products(p_codigo text)
returns table (
  tienda_id bigint,
  tienda_nombre text,
  producto_id bigint,
  sku text,
  articulo text,
  unidad text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Inicia el acceso de operador primero'; end if;
  return query
  select t.id, t.nombre, p.id, p.codigo_barras, p.nombre_producto, p.unidad
  from public.tiendas t
  join public.productos p on p.tienda_id = t.id and p.es_critico
  where upper(t.codigo_critico) = upper(trim(p_codigo))
  order by p.nombre_producto;
  if not found then raise exception 'Código incorrecto o la tienda no tiene artículos críticos'; end if;
end;
$$;

create or replace function public.submit_critical_daily_count(p_codigo text, p_operador text, p_capturas jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tienda_id bigint;
  v_fecha date := (now() at time zone 'America/Mexico_City')::date;
  v_conteo_id bigint;
  v_operador_existente text;
  v_estado text;
  v_total_criticos bigint;
  v_total_capturas bigint;
  v_capturas_unicas bigint;
begin
  if auth.uid() is null then raise exception 'Inicia el acceso de operador primero'; end if;
  if trim(coalesce(p_operador, '')) = '' then raise exception 'Escribe el nombre de quien realizó el conteo'; end if;
  if coalesce(jsonb_typeof(p_capturas), '') <> 'array' then raise exception 'La captura debe incluir una cantidad por artículo'; end if;

  select t.id into v_tienda_id
  from public.tiendas t
  where upper(t.codigo_critico) = upper(trim(p_codigo));
  if not found then raise exception 'Código de sucursal incorrecto'; end if;

  select count(*) into v_total_criticos
  from public.productos p
  where p.tienda_id = v_tienda_id and p.es_critico;

  select count(*), count(distinct item.producto_id)
    into v_total_capturas, v_capturas_unicas
  from jsonb_to_recordset(p_capturas) as item(producto_id bigint, cantidad numeric);

  if v_total_criticos = 0 then raise exception 'La sucursal no tiene artículos críticos'; end if;
  if v_total_capturas <> v_total_criticos or v_capturas_unicas <> v_total_criticos then
    raise exception 'Captura todos los artículos críticos una sola vez';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_capturas) as item(producto_id bigint, cantidad numeric)
    where item.cantidad is null or item.cantidad < 0
  ) then raise exception 'Las cantidades deben ser cero o mayores'; end if;
  if exists (
    select 1 from jsonb_to_recordset(p_capturas) as item(producto_id bigint, cantidad numeric)
    left join public.productos p on p.id = item.producto_id
    where p.id is null or p.tienda_id <> v_tienda_id or not p.es_critico
  ) then raise exception 'La captura contiene un artículo que no pertenece a esta sucursal'; end if;

  insert into public.conteos_criticos_diarios (tienda_id, fecha, operador_nombre)
  values (v_tienda_id, v_fecha, trim(p_operador))
  on conflict (tienda_id, fecha) do nothing;

  select cc.id, cc.operador_nombre, cc.estado
    into v_conteo_id, v_operador_existente, v_estado
  from public.conteos_criticos_diarios cc
  where cc.tienda_id = v_tienda_id and cc.fecha = v_fecha
  for update;

  if lower(v_operador_existente) <> lower(trim(p_operador)) then
    raise exception 'El conteo de hoy ya fue enviado por %', v_operador_existente;
  end if;
  if v_estado = 'revisado' then raise exception 'El gerente ya revisó el conteo de hoy'; end if;

  insert into public.conteos_criticos_detalle (conteo_id, producto_id, cantidad_contada)
  select v_conteo_id, item.producto_id, item.cantidad
  from jsonb_to_recordset(p_capturas) as item(producto_id bigint, cantidad numeric)
  on conflict (conteo_id, producto_id)
  do update set cantidad_contada = excluded.cantidad_contada;

  return v_conteo_id;
end;
$$;

revoke all on function public.get_critical_store_products(text) from public;
revoke all on function public.submit_critical_daily_count(text, text, jsonb) from public;
grant execute on function public.get_critical_store_products(text) to anon, authenticated;
grant execute on function public.submit_critical_daily_count(text, text, jsonb) to anon, authenticated;